### ISSUE TITLE
[BUG] Attempt to import example fails

### ISSUE THREAD

**Issue by lo-co** [nxp-mcuxpresso/vscode-for-mcux#10]
OS: Ubuntu 20.04
VS Code:  Version 1.81.1
MCUXpresso for VS Code: 1.0.68

Attempting to import from a repository as shown:

![image](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/9597736/57dfa5d4-c196-4277-a93a-63da72bc73de)

Get this error:

![image](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/9597736/5907cb84-d02c-48f7-a081-242de820574f)

**Comment by lo-co** [comment]
This happens when I use a local folder for the SDK.

**Comment by DragosMiloiuNXP** [comment]
Hi @lo-co, we did not reproduce the error. Could you please share more details about the way you created the repository?

**Comment by DragosMiloiuNXP** [comment]
> Hi @lo-co, we did not reproduce the error. Could you please share more details about the way you created the repository?

We reproduced the issue locally. It will be fixed in the next release which will be available at the end of this month.

**Comment by DragosMiloiuNXP** [comment]
Hi @lo-co, latest published version fixes this issue.

**Comment by lo-co** [comment]
I will check it out.  Thanks @DragosMiloiuNXP.
