### ISSUE TITLE
Restrict 'Go to Definition' to the relevant board only

### ISSUE THREAD

**Issue by escherstair** [nxp-mcuxpresso/vscode-for-mcux#12]
I installed the extension and I imported an example from the repository, where I select the evaluation board `evkmimx8mp` in the SDK.
In `mcuxpresso-tools.json` I can see
```json
  "sdk": {
    "version": "2.14.0",
    "path": "d:\\repos\\SDK_NXP",
    "boardId": "evkmimx8mp",
    "deviceId": "MIMX8ML8xxxLZ",
    "coreId": "cm7_MIMX8ML8xxxLZ",
    "manifestId": "SDK_2.x_EVK-MIMX8MP_manifest_v3_13"
  }
```
When I use the "Go to Definition F12' feature over the function `BOARD_InitMemory()`, a lot of possiiblities are shown:
![immagine](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/22594460/9e5745c8-ab98-4fc6-b052-2b34b95065a7)
They're from all the boards available in the SDK.
Is there a way to "restrict" these possiiblities to the board selected in the SDK only?

**Comment by cristitep-nxp** [comment]
Hi,

This is a feature inside Microsoft C/C++ extension. The good part I see in my tests and also in your picture is that the proper definition is focused so you can easily go to the right code.
On the other hand I see some other people raised the same problem https://github.com/microsoft/vscode-cpptools/issues/6471 with a suggested workaround but having some potential side effects (see C_Cpp.definitions.exclude setting) and a potential fix not accepted so far.

Regards,
Cristian

**Comment by escherstair** [comment]
Closed because it's not a vscode-for-mcux issue
