### ISSUE TITLE
Add include paths to zephyr

### ISSUE THREAD

**Issue by MaxOvervoordee** [nxp-mcuxpresso/vscode-for-mcux#13]
Hi,

Is there an easy way to add include paths to your project in zephyr?
Just like you could normally do in C/C++ Build>Settings>Tool Settings>Includes>Include Paths.

**Comment by MaxOvervoordee** [comment]
Hi @DerekSnell Thank you for your fast answer.
I've tried what you said, building seems to be correct in the output terminal.
Now i only get one more error, the first include of my main:
`#include "mc_periph_init.h"`
When ctrl clicking this include it does show me the correct file in lib/motor_cource/mc_periph_init.h
I included the next code, with many directories according to your example: `target_include_directories(app PRIVATE lib/motor_source)`
Could you help me figure out what i'm doing wrong?

**Comment by DerekSnell** [comment]
Hello @MaxOvervoordee ,

Perhaps an example will help.  [hello_world_include.zip](https://github.com/nxp-mcuxpresso/vscode-for-mcux/files/12810072/hello_world_include.zip) uses the same include path and filename that you listed.  You can import this as a Project Archive into the MCUXpresso extension for VS Code.

Let us know how this works for you.  Best regards

**Comment by MaxOvervoordee** [comment]
@DerekSnell Thank you.

For some more context, i've been working on a motor FOC example in MCUXpresso for some time, and i'm trying to convert/transfer that code to the zephyr os. I was told as zephyr includes the global libraries of supported board, it should be doable. 
The way i'm doing that rn is just copy pasting library folders into zephyr and getting them in the directory using the method you suggest.

The build shows two error of the following kind:
`conflicting types for 'int32_t'; have 'long int'`
`> previous declaration of 'int32_t' with type 'int32_t' {aka 'int'}`

Does this mean the other code doesn't have errors or just that these are the first errors it has encountered therefore stopped immediately?
And is there maybe a more recommended way to convert code and libraries made in mcuxpresso to zephyrOS?

**Comment by DerekSnell** [comment]
Hi @MaxOvervoordee ,
Your latest response seems unrelated to the original topic of this Issue.  Can you create a new Issue for each topic?  You can link existing issues and discussions in the new Issues for context.  But others struggling with similar issues will have an easier time finding these solutions if the discussions are all related to the title of the Issue.  And for our tracking purposes and ensuring we resolve all issues, it is best to keep each topic separate, so we can address them all.

As for the original include path issue, I assume the example helped you find your header file.  Are you ready to close this Issue now?

Thanks
