### ISSUE TITLE
Remote debug using j-link

### ISSUE THREAD

**Issue by alireza-bp** [nxp-mcuxpresso/vscode-for-mcux#2]
I can't find an option in the "launch.json" file to add the address of a remote server and configure it for debugging programs using a J-Link that is connected to a remote PC. While this option is present in several other extensions, it appears to be absent in MCUXpresso.

**Comment by DragosMiloiuNXP** [comment]
Hi @alireza-bp, thanks for reporting the issue. It will be addressed in the next release.

**Comment by DragosMiloiuNXP** [comment]
The latest version of the extension includes support for debugging using a remote GDB server.

Please have a look at [documentation](https://github.com/nxp-mcuxpresso/vscode-for-mcux/wiki/Debug#remote-gdb-server) for steps on how to use it.
