### ISSUE TITLE
MCUXpresso Installer doesn't install Arm GNU Toolchain add-ons

### ISSUE THREAD

**Issue by escherstair** [nxp-mcuxpresso/vscode-for-mcux#22]
I installed MCUXpresso Installer v1.1 b155 on my Windows 10 PC.
I select MCUXpresso SDK Developer to be installed
![immagine](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/22594460/28593a01-986e-4b49-bb44-6d67cf295864)

If I hover with the mouse, I see that Arm GNU Toolchain add-ons is one of the items that will be installed
![immagine](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/22594460/193d05fb-e30f-40e4-aad4-61afa3f3b69f)

But it's not instaleed.

I'm able to install it if I select the Individual Component "Arm GNU Toolchain add-ons".
![immagine](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/22594460/f11c88d5-b612-4eb8-8f1f-13b7e99e2646)

**Comment by cristitep-nxp** [comment]
Hi,

"Arm GNU Toolchain add-ons" is a pack of files which (automatically) comes on top of "Arm GNU Toolchain" when this component is part of the installation. This is the case of "Arm Gnu Toolchain" from "Individual Components" and from "MCUXpresso SDK Developer". And this is indicated on their tooltips.
Additionally, we had a request to provide a standalone version of the pack that can be placed on the top of a custom/user's distribution of "Arm GNU Toolchain" - which doesn't originally have our extra pack. And this is the purpose of this "Arm GNU Toolchain add-ons" standalone pack under Individual Components.
So you actually might have the situation when "Arm GNU Toolchain" reports that it has the pack on top while individual pack was not downloaded (your case). This is better explained on https://github.com/nxp-mcuxpresso/vscode-for-mcux/wiki/Dependency-Installation#additional-individual-components .
Indeed, this might be confusing and we'll think on a way to better represent this situation.

Regards,
Cristian

**Comment by escherstair** [comment]
Thanks.
Your explanation is really clear. The actual situation is a little bit confusing, but I understand.

**Comment by escherstair** [comment]
Hi @cristitep-nxp 
I have another question on "Arm GNU Toolchain add-ons".
With MCUXpresso Installer, everything is ok on my development laptop.

But now I need to setup the environment to build my SDK-based project on CI pipeline.
I download the ARM GNU Toolchain from [here](https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads).
Where I can download "Arm GNU Toolchain add-ons"?
Is there a public download link?

Thanks

**Comment by escherstair** [comment]
Hi @cristitep-nxp 
sorry for pushing, bau can you (or someone else from NXP) point me to the link to download "Arm GNU Toolchain add-ons" in my CI pipeline?
Thanks

**Comment by cristitep-nxp** [comment]
Hi,

Sorry for delay, MCUXpresso Installer places in log the location from where it downloads. In this case:
https://www.nxp.com/lgfiles/updates/mcuxpresso/AdditionalCLibs-12.2.1-win32.zip

Anyway, for additional links that you might need: from Installer -> Toolbar -> Open log folder -> go up one dir -> go to .cache dir -> open components.json -> all locations are there (including "Arm GNU Toolchain add-ons")

After download: unzip -> you'll get an ARM GCC dir (latest is arm-gnu-toolchain-12.2.rel1-mingw-w64-i686-arm-none-eabi) which has a similar dir structure with an ARM GCC -> copy its content on the root dir of your arm gcc layout.

**Comment by escherstair** [comment]
Thank you.
It works perfectly
