### ISSUE TITLE
MCUXpresso SDK version not shown

### ISSUE THREAD

**Issue by escherstair** [nxp-mcuxpresso/vscode-for-mcux#23]
I have a project and I'm able to build it without any issue.

- Installed repositories show SDK_2.x_MIMX8ML8xxxKZ (downloaded as a zip file from [MCUXpresso SDK Builder](https://mcuxpresso.nxp.com/en/welcome) and imported as Local repository
- file `mcuxpresso-tools.json` shows the right SDK version `2.14.0`
- Project >> Repository information shows the right Type, Path and ID; but the Version is <Repository not installed>

![immagine](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/22594460/bfa5d2ff-9263-41ff-a380-71f26cbab00a)

Is this a bug?

**Comment by DragosMiloiuNXP** [comment]
Hi @escherstair,

Right now, in mcuxpresso-tools.json you can define your paths (like: toolchainPath, sdk.path, etc.) only by using the value of environment variables. Example: "toolchainPath": "%HOMEPATH%/.mcuxpressotools/arm-gnu-toolchain-12.2.rel1-mingw-w64-i686-arm-none-eabi". 

The {workspaceFolder} is not supported, but it should be. I'll add support for it in the next version.

**Comment by escherstair** [comment]
Understood.
Thanks

**Comment by cristitep-nxp** [comment]
This is resolved now in the latest build 1.4.63

**Comment by escherstair** [comment]
I confirm this.
Thanks.
