### ISSUE TITLE
ide_overrides.cmake with wrong line-ending on Windows

### ISSUE THREAD

**Issue by escherstair** [nxp-mcuxpresso/vscode-for-mcux#28]
As far as I understand, `*.cmake` files should have **native** line-endings (i.e., `LF` on Linux and `CRLF` on Windows).
I work on Windows and I noticed that when `ide_overrides.cmake` is re-generated (I see that it's generated when I click on `Build Selected` from extension), `LF` is used.
And it should be CRLF on Windows.

**Comment by cristitep-nxp** [comment]
Hi @escherstair,

We will fix it in the next release.

Thanks!

**Comment by DragosMiloiuNXP** [comment]
This is fixed in the latest release - v1.4.63.
