### ISSUE TITLE
CMake: Some vendor provided library does not exist

### ISSUE THREAD

**Issue by imi415** [nxp-mcuxpresso/vscode-for-mcux#3]
The projects requires the following libraries which relies on the NXP supplied toolchain only:
`cr_newlib_{semihost, nohost, none}`
which caused problems on ARM GNU Toolchain or other distribution toolchains.

```
.../arm-gnu-toolchain-12.2.mpacbti-rel1-x86_64-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/12.2.1/../../../../arm-none-eabi/bin/ld: cannot find -lcr_newlib_nohost: No such file or directory
```

**Comment by cristitep-nxp** [comment]
Additional NXP supplied toolchain libs are intended to provide various debugger functionalities (i.e. semihosting, stubs for no hosting, heap monitoring, …). Still, if you need your own ARM GNU toolchain version, the easiest workaround now is to install a toolchain using MCUXpresso Installer. Then go to the downloaded additional supplied pack (i.e. for Windows with latest pack: C:\Users\<user>\AppData\Local\Programs\MCUXpressoInstaller\.cache\AdditionalCLibs-10.3-2021.10-win32-VSC.zip) and unzip it over your desired toolchain (the folder hierarchy from zip is a top ARM GNU toolchain path dir). Of course, this might create some compatibility issues depending on your desired toolchain version.

PS. We plan to make this operation possible in an automated fashion in a next version using the MCUXpresso Installer.

**Comment by KafCoppelia** [comment]
Is it possible to provide a link to enable the installation of additional features provided by NXP?

**Comment by cristitep-nxp** [comment]
Hi,

Go to MCUXpresso Installer:
![image](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/98579057/e664b57f-0b12-4e16-bf7e-6ce0ee53925f)

And install the toolchain addon:
![image](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/98579057/7fecdc14-e604-47fe-9586-d38e835508ee)

Regards,
Cristian
