### ISSUE TITLE
MCUXpresso Installer could not download file dtc-1.6.1-1-x86_64.pkg.tar.zst

### ISSUE THREAD

**Issue by yuhuaxia** [nxp-mcuxpresso/vscode-for-mcux#38]
Hi All,

During "Zephyr Developer" installation, the MCUXpresso Installer failed  to download https://repo.msys2.org/msys/x86_64/dtc-1.6.1-1-x86_64.pkg.tar.zst
When I check https://repo.msys2.org/msys/x86_64, there is only dtc-1.6.1-2-x86_64.pkg.tar.zst and dtc-1.6.1-3-x86_64.pkg.tar.zst
I tried work around it by:
1. Download dtc-1.6.1-2-x86_64.pkg.tar.zst manully
2. Put it to %HOME%\AppData\Local\Programs\MCUXpressoInstaller\.cache\
3. Change its name to dtc-1.6.1-1-x86_64.pkg.tar.zst.
4. Try install "Zephyr Developer" again
But the installer say "Hash mismatch .." and insist on downloading the non-existent vdtc-1.6.1-1-x86_64.pkg.tar.zst
Pls help to fix.

**Comment by LorenaLazarNXP** [comment]
Hi @yuhuaxia,

Thank you for your report!
We have just made a fix. Open the MCUXpresso Installer and install "Zephyr Developer" category, it should work right now.
Please, let us know if the issue is fixed!

Have a good day,
Lorena Lazar
