### ISSUE TITLE
Unable to import Zephyr repository

### ISSUE THREAD

**Issue by rmars-fedsig** [nxp-mcuxpresso/vscode-for-mcux#5]
I'm trying to import a Zephyr repository using the new MCUXpresso for VS code extension (v0.9.64). I've created a zephyr project using the following as specified in the Zephyr home page. 

cd %HOMEPATH%
west init zephyrproject
cd zephyrproject
west update

Using the "Local" tab under Import Repository and specifying "zephyrproject" as the location given the Zephyr project was created via the Zephyr website instructions. But when doing so I receive the following error. 

Error: Not a valid MCUXpresso SDK, Zephyr or Open-CMSIS-Pack repository

**Comment by cristitep-nxp** [comment]
I tried with the command you gave, then import from Local with the absolute path, so "C:\Users\<my_user>\zephyrproject" and everything seems to be working. I also tried as you specified exactly so "zephyrproject" name only, but this does not enable "Import" button as this is not recognized as a valid path.
Please let us know if you didn't solve this, there is a chance that somehow your west commands did not complete successfully, so need some additional info:
- check if you have the following directories in your zephyrproject\zephyr: "boards", "samples", "tests","Kconfig.zephyr"
- check the west version you have (“west --version”) – we might need to try the same
- can you share the output of the “west list” command?

**Comment by rmars-fedsig** [comment]
I ended up deleting my original zephyrproject and recreated/reinstalled using the zephyr home page. I was then able to import the new zephyrproject. I’m assuming I missed something in the installation. The checklist you provided should be helpful in the future.

Thank you for your help.


RussellMars | Firmware Engineer
Federal Signal
 | 2645 Federal Signal Drive | University Park, Illinois 60484
 |  
www.fedsig.com |  
This correspondence may contain confidential information intended for the use of the individual or entity to which it is addressed. If the reader of this electronic message is not the intended recipient, or the employee or agent responsible to deliver it to the intended recipient, you are hereby notified that any dissemination, distribution or copying is strictly prohibited. If you have received this e-mail in error, please notify the sender immediately by e-mail and immediately destroy this e-mail and its attachments.
