### ISSUE TITLE
Support for Fedora

### ISSUE THREAD

**Issue by MJAS1** [nxp-mcuxpresso/vscode-for-mcux#55]
This cannot currently be used with RPM-based Linux distributions due to MCUXpressInstaller only distributed in deb format. Are there any plans on supporting Fedora?

**Comment by cristitep-nxp** [comment]
Hi,

We have no short term plan to support rpm-based linux.

Regards,
Cristian

**Comment by dylad** [comment]
Even if no .rpm binary are provided, It seems possible to install the extension through vscode directly.

The biggest 'issue' was to manually create Python venv.
