### ISSUE TITLE
Dependency Installation missing critical bits

### ISSUE THREAD

**Issue by ajlennon** [nxp-mcuxpresso/vscode-for-mcux#7]
Dependency Installation section doesn't tell me where to find and run the UI executable after the .bin installs the dpkg

`/usr/local/MCUXpressoInstaller/MCUXpressoInstaller`

**Comment by cristitep-nxp** [comment]
This will be fixed in the next installer version (end of July)

**Comment by ajlennon** [comment]
Thanks @cristitep-nxp

**Comment by DragosMiloiuNXP** [comment]
Installer now outputs the destination path.

![image](https://github.com/nxp-mcuxpresso/vscode-for-mcux/assets/80047870/45051287-e20d-415b-ac9c-757415f46fa7)
