### ISSUE TITLE
Suggest use HOME folder as the default location for select local folder prompt

### ISSUE THREAD

**Issue by yvesll** [nxp-mcuxpresso/vscode-for-mcux#9]
In Linux, HOME folder is more usable than the default root folder.

**Comment by DragosMiloiuNXP** [comment]
@yvesll, we will implement this in a future release. Please note that this will apply only to our UI (VS Code standard views will still use root folder as default location).

**Comment by DragosMiloiuNXP** [comment]
This issue is fixed in the latest version (1.2.49).
